// Code generated by protoc-gen-stringer. DO NOT EDIT.
// source: example/example2.proto
package example

var enumStringMapFoop_string = map[Foop]string{
	Foop_Foo1p:        "Foo1",
	Foop_Foo2p:        "Foo2",
	Foop_Foop_Unknown: "Unknown",
}

var enumStringVarFoop_val = map[string]Foop{
	"Foo1":    Foop_Foo1p,
	"Foo2":    Foop_Foo2p,
	"Unknown": Foop_Foop_Unknown,
}

func (i Foop) StringVal() string {
	return enumStringMapFoop_string[i]
}

func StringToFoop(s string) (Foop, bool) {
	val, ok := enumStringVarFoop_val[s]
	return val, ok
}

var enumStringMapBarp_string = map[Barp]string{
	Barp_Bar1p:        "Bar1",
	Barp_Bar2p:        "Bar2",
	Barp_Barp_Unknown: "Unknown",
}

var enumStringVarBarp_val = map[string]Barp{
	"Bar1":    Barp_Bar1p,
	"Bar2":    Barp_Bar2p,
	"Unknown": Barp_Barp_Unknown,
}

func (i Barp) StringVal() string {
	return enumStringMapBarp_string[i]
}

func StringToBarp(s string) (Barp, bool) {
	val, ok := enumStringVarBarp_val[s]
	return val, ok
}
