// Code generated by protoc-gen-stringer. DO NOT EDIT.
// source: example/example.proto
package example

var enumStringMapFoo_string = map[Foo]string{
	Foo_Foo1:        "Foo1",
	Foo_Foo2:        "Foo2",
	Foo_Foo_Unknown: "Unknown",
}

var enumStringVarFoo_val = map[string]Foo{
	"Foo1":    Foo_Foo1,
	"Foo2":    Foo_Foo2,
	"Unknown": Foo_Foo_Unknown,
}

func (i Foo) StringVal() string {
	return enumStringMapFoo_string[i]
}

func StringToFoo(s string) (Foo, bool) {
	val, ok := enumStringVarFoo_val[s]
	return val, ok
}

var enumStringMapBar_string = map[Bar]string{
	Bar_Bar1:        "Bar1",
	Bar_Bar2:        "Bar2",
	Bar_Bar_Unknown: "Unknown",
}

var enumStringVarBar_val = map[string]Bar{
	"Bar1":    Bar_Bar1,
	"Bar2":    Bar_Bar2,
	"Unknown": Bar_Bar_Unknown,
}

func (i Bar) StringVal() string {
	return enumStringMapBar_string[i]
}

func StringToBar(s string) (Bar, bool) {
	val, ok := enumStringVarBar_val[s]
	return val, ok
}
