// Code generated by protoc-gen-stringer. DO NOT EDIT.
// source: example/example2.proto
package example

import "fmt"

const enumStringVarFoop = "Foo1Foo2Unknown"

var enumStringVarIndexFoop = [...]uint8{0, 4, 8, 15}

func (i Foop) StringVal() string {
	if i < 0 || i+1 >= Foop(len(enumStringVarIndexFoop)) {
		return fmt.Sprintf("%d", i)
	}
	return enumStringVarFoop[enumStringVarIndexFoop[i]:enumStringVarIndexFoop[i+1]]
}
func StringToFoop(s string) Foop {
	switch s {
	case "Foo1":
		return Foop_Foo1p
	case "Foo2":
		return Foop_Foo2p
	case "Unknown":
		return Foop_Foop_Unknown
	default:
		return 0
	}
}

const enumStringVarBarp = "Bar1Bar2Unknown"

var enumStringVarIndexBarp = [...]uint8{0, 4, 8, 15}

func (i Barp) StringVal() string {
	if i < 0 || i+1 >= Barp(len(enumStringVarIndexBarp)) {
		return fmt.Sprintf("%d", i)
	}
	return enumStringVarBarp[enumStringVarIndexBarp[i]:enumStringVarIndexBarp[i+1]]
}
func StringToBarp(s string) Barp {
	switch s {
	case "Bar1":
		return Barp_Bar1p
	case "Bar2":
		return Barp_Bar2p
	case "Unknown":
		return Barp_Barp_Unknown
	default:
		return 0
	}
}
