// Code generated by protoc-gen-stringer. DO NOT EDIT.
// source: tests/simple/simple.proto
package simple

var enumStringMapExample_string = map[Example]string{
	Example_exampleBar1:  "exampleBar1",
	Example_exampleBar2:  "exampleBar2",
	Example_exampleBar3:  "exampleBar3",
	Example_exampleBar4:  "exampleBar4",
	Example_exampleBar5:  "exampleBar5",
	Example_exampleBar6:  "exampleBar6",
	Example_exampleBar7:  "exampleBar7",
	Example_exampleBar8:  "exampleBar8",
	Example_exampleBar9:  "exampleBar9",
	Example_exampleBar10: "exampleBar10",
}

var enumStringVarExample_val = map[string]Example{
	"exampleBar1":  Example_exampleBar1,
	"exampleBar2":  Example_exampleBar2,
	"exampleBar3":  Example_exampleBar3,
	"exampleBar4":  Example_exampleBar4,
	"exampleBar5":  Example_exampleBar5,
	"exampleBar6":  Example_exampleBar6,
	"exampleBar7":  Example_exampleBar7,
	"exampleBar8":  Example_exampleBar8,
	"exampleBar9":  Example_exampleBar9,
	"exampleBar10": Example_exampleBar10,
}

func (i Example) StringVal() string {
	return enumStringMapExample_string[i]
}

func StringToExample(s string) (Example, bool) {
	val, ok := enumStringVarExample_val[s]
	return val, ok
}
