// Code generated by protoc-gen-stringer. DO NOT EDIT.
// source: tests/double/simple.proto
package double

var enumStringMapExample_string = map[Example]string{
	Example_exampleBar0:     "exampleBar0",
	Example_exampleBar2:     "exampleBar2",
	Example_exampleBarEmpty: "Example_exampleBarEmpty",
	Example_exampleBar4:     "exampleBar4",
	Example_exampleBar5:     "exampleBar5",
	Example_exampleBar6:     "exampleBar6",
	Example_exampleBar7:     "exampleBar7",
	Example_exampleBar8:     "exampleBar8",
	Example_exampleBar9:     "exampleBar9",
}

var enumStringVarExample_val = map[string]Example{
	"exampleBar0":             Example_exampleBar0,
	"exampleBar2":             Example_exampleBar2,
	"Example_exampleBarEmpty": Example_exampleBarEmpty,
	"exampleBar4":             Example_exampleBar4,
	"exampleBar5":             Example_exampleBar5,
	"exampleBar6":             Example_exampleBar6,
	"exampleBar7":             Example_exampleBar7,
	"exampleBar8":             Example_exampleBar8,
	"exampleBar9":             Example_exampleBar9,
}

func (i Example) StringVal() string {
	return enumStringMapExample_string[i]
}

func StringToExample(s string) (Example, bool) {
	val, ok := enumStringVarExample_val[s]
	return val, ok
}

var enumStringMapExample3_string = map[Example3]string{
	Example3_example3Bar0: "exampleBar0",
	Example3_example3Bar1: "Example3_example3Bar1",
	Example3_example3Bar2: "Example3_example3Bar2",
	Example3_example3Bar4: "Example3_example3Bar4",
	Example3_example3Bar5: "Example3_example3Bar5",
	Example3_example3Bar6: "Example3_example3Bar6",
	Example3_example3Bar7: "Example3_example3Bar7",
	Example3_example3Bar8: "Example3_example3Bar8",
	Example3_example3Bar9: "Example3_example3Bar9",
}

var enumStringVarExample3_val = map[string]Example3{
	"exampleBar0":           Example3_example3Bar0,
	"Example3_example3Bar1": Example3_example3Bar1,
	"Example3_example3Bar2": Example3_example3Bar2,
	"Example3_example3Bar4": Example3_example3Bar4,
	"Example3_example3Bar5": Example3_example3Bar5,
	"Example3_example3Bar6": Example3_example3Bar6,
	"Example3_example3Bar7": Example3_example3Bar7,
	"Example3_example3Bar8": Example3_example3Bar8,
	"Example3_example3Bar9": Example3_example3Bar9,
}

func (i Example3) StringVal() string {
	return enumStringMapExample3_string[i]
}

func StringToExample3(s string) (Example3, bool) {
	val, ok := enumStringVarExample3_val[s]
	return val, ok
}
